import { Link } from "react-router";

const sections = [
  {
    title: "1. Information We Collect",
    body: `We collect information you provide directly during registration (name, email address, and any identity verification documents required), information generated by your use of the platform (transaction records, investment activity, wallet balances, support communications), and technical information (IP addresses, device identifiers, browser type) collected automatically during platform access.`,
  },
  {
    title: "2. How We Use Your Information",
    body: `We use collected information to: operate and maintain your account and wallet; process deposits, investments, and withdrawal requests; calculate and apply investment accruals; send transactional notifications; verify your identity where required; comply with legal and regulatory obligations; detect, investigate, and prevent fraud or unauthorized activity; and improve the platform.`,
  },
  {
    title: "3. Data Storage and Security",
    body: `Your data is stored in a secured database with industry-standard access controls. Passwords are stored using cryptographic hashing — never in plain text. Row-level security policies ensure that your data is only accessible by your authenticated session and authorized platform administrators. Access to sensitive data is logged.`,
  },
  {
    title: "4. Data Sharing",
    body: `We do not sell your personal data. We may share data with: (a) our payment processing provider, solely as required to process deposits; (b) identity verification providers, where verification is required; (c) legal authorities, where required by law or court order; (d) service providers operating on our behalf under confidentiality agreements. We do not share your data with third parties for marketing purposes.`,
  },
  {
    title: "5. Cookies and Tracking",
    body: `The platform uses session cookies for authentication and security purposes. We do not use third-party advertising trackers. Essential cookies required for platform operation cannot be disabled. You may adjust non-essential cookie settings in your browser, though this may affect platform functionality.`,
  },
  {
    title: "6. Data Retention",
    body: `We retain your account data for the duration of your account and for a period thereafter as required by applicable law, typically up to seven years for financial records. Transaction records are retained for regulatory compliance purposes. You may request deletion of your personal data, subject to our legal retention obligations.`,
  },
  {
    title: "7. Your Rights",
    body: `Depending on your jurisdiction, you may have the right to access, correct, delete, or export your personal data. To exercise these rights, contact us at compliance@musk-enterprise.com. We will respond within the timeframe required by applicable law.`,
  },
  {
    title: "8. Children",
    body: `The platform is not intended for individuals under 18 years of age. We do not knowingly collect personal data from minors. If we become aware that a minor has registered, we will terminate the account and delete associated data.`,
  },
  {
    title: "9. Changes to This Policy",
    body: `We may update this Privacy Policy from time to time. Material changes will be communicated to registered users. Continued use of the platform following an update constitutes acceptance of the revised policy.`,
  },
];

export default function Privacy() {
  return (
    <div className="fade-up pt-32 pb-24 px-6 md:px-10">
      <div className="max-w-3xl mx-auto">
        <div className="mb-12">
          <p className="text-xs font-semibold uppercase tracking-widest mb-3" style={{ color: "#d4a017" }}>Legal</p>
          <h1 className="text-4xl md:text-5xl font-black tracking-tight mb-4" style={{ letterSpacing: "-0.04em" }}>
            Privacy Policy
          </h1>
          <p className="text-sm" style={{ color: "#9090a8" }}>Last updated: January 2025</p>
        </div>

        <div className="p-6 mb-10 border-l-2 text-sm" style={{ borderColor: "#d4a017", background: "#111118", color: "#9090a8" }}>
          This Privacy Policy describes how Musk Enterprise collects, uses, stores, and protects your personal information when you use our platform.
        </div>

        <div className="space-y-10">
          {sections.map((s, i) => (
            <div key={i}>
              <h2 className="text-base font-bold mb-3">{s.title}</h2>
              <p className="text-sm leading-relaxed" style={{ color: "#9090a8" }}>{s.body}</p>
            </div>
          ))}
        </div>

        <div className="mt-16 pt-8 border-t flex flex-wrap gap-4" style={{ borderColor: "rgba(212,160,23,0.15)" }}>
          <Link to="/terms" className="text-sm" style={{ color: "#d4a017" }}>Terms of Service →</Link>
          <Link to="/risk-disclosure" className="text-sm" style={{ color: "#d4a017" }}>Risk Disclosure →</Link>
          <Link to="/contact" className="text-sm" style={{ color: "#d4a017" }}>Contact →</Link>
        </div>
      </div>
    </div>
  );
}
